name: 云端自动打包 APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  android:
    name: 打包 Android APK
    runs-on: ubuntu-latest

    steps:
      - name: 代码迁出
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 构建 Java 环境
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: 安装对应版本的 Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: 应用 PiliPlus 框架补丁
        shell: pwsh
        run: lib/scripts/patch.ps1 android

      - name: 生成版本信息与编译配置文件
        shell: pwsh
        run: lib/scripts/build.ps1 android

      - name: 安装项目依赖
        run: flutter pub get

      - name: 打包 release APK
        run: flutter build apk --release --dart-define-from-file=pili_release.json --pub

      - name: 自动发布到 Releases (任何人免登录直接下载)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v2.1.0-title-filter
          name: "PiliPlus v2.1.0 标题筛选定制版"
          body: "本版本增加了视频标题关键词严格筛选功能。"
          draft: false
          prerelease: false
          files: build/app/outputs/flutter-apk/*.apk
